name: predict next matchday

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * 5'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
    - name: Say hello, install package and predict next matchday
      run: |-
        sudo python3 setup.py install
        cd sandbox/predict_next_matchday
        python3 predict_next_matchday.py
    - name: Git update if changed
      run: |-
        git config user.name "Scheduled Predictor"
        git config user.email "actions@users.noreply.github.com"
        git config pull.rebase false
        git add sandbox/predict_next_matchday/
        git commit -m "predicted next matchday"
        git pull
        git push
